---
Resources:
  VPCTest:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/24
      EnableDnsHostnames: false
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags: 
        - Key: Name
          Value: VPCTest
  
  PrivateSubnetTest:
    Type: AWS::EC2::Subnet
    DependsOn: VPCTest
    Properties:
      # Can only specify either AvailabilityZone or AvailabilityZoneId, NOT both.
      AvailabilityZone: ap-southeast-1a
      # AvailabilityZoneId: apse1-az2

      CidrBlock: 10.0.0.0/28
      # MapPublicIpOnLaunch: true # Indicates whether instances launched in this subnet receive a public IPv4 address. The default value is false.
      Tags: 
        - Key: Name
          Value: PrivateSubnetTest
      VpcId: !GetAtt VPCTest.VpcId

  # PublicSubnetTest:
  #   Type: AWS::EC2::Subnet
  #   Properties:
  #     AssignIpv6AddressOnCreation: Boolean
  #     AvailabilityZone: String
  #     AvailabilityZoneId: String
  #     CidrBlock: String
  #     EnableDns64: Boolean
  #     Ipv6CidrBlock: String
  #     Ipv6Native: Boolean
  #     MapPublicIpOnLaunch: Boolean
  #     OutpostArn: String
  #     PrivateDnsNameOptionsOnLaunch: 
  #       PrivateDnsNameOptionsOnLaunch
  #     Tags: 
  #       - Tag
  #     VpcId: String
